export const MEMBERSHIP_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  LEFT: 'LEFT',
} as const

export const PROJECT_STATUS = {
  IDEA: 'IDEA',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
} as const

export const ERROR_CODE = {
  AUTH: 'auth_violation',
  CROSS_ORG: 'cross_org_violation',
  OPERATION_FAILED: 'operation_failed',
  ACCESS_DENIED: 'access_denied',
} as const

export const PROJECT_ROLE = {
  OWNER: 'OWNER',
  EDITOR: 'EDITOR',
  VIEWER: 'VIEWER',
} as const

export const PROJECT_AUDIT_ACTION = {
  MEMBER_ADDED: 'MEMBER_ADDED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
} as const

export const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
} as const

export const MEMBERSHIP_ROLE = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  CHAIR: 'CHAIR',
  MEMBER: 'MEMBER',
} as const

export const MEDIA_CATEGORY = {
  BEFORE: 'BEFORE',
  AFTER: 'AFTER',
  PROTOCOL: 'PROTOCOL',
  DESCRIPTION: 'DESCRIPTION',
} as const

export const MEDIA_OBJECT_TYPE = {
  PROJECT: 'PROJECT',
  MEETING: 'MEETING',
} as const

export const RESOLUTION_STATUS = {
  DRAFT: 'DRAFT',
  PROPOSED: 'PROPOSED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const

export const RESOLUTION_VISIBILITY = {
  PUBLIC: 'PUBLIC',
  MEMBERS: 'MEMBERS',
  INTERNAL: 'INTERNAL',
} as const

export const CONSENT_TYPE = {
  CORE_STATUTES: 'CORE_STATUTES',
  CHARTER: 'CHARTER',
  TERMS: 'TERMS',
  PRIVACY: 'PRIVACY',
  INTERNAL_RULES: 'INTERNAL_RULES',
} as const

export type ConsentType = typeof CONSENT_TYPE[keyof typeof CONSENT_TYPE]

export const CHAIRMAN_REQUIRED_CONSENTS: ConsentType[] = [
  CONSENT_TYPE.CORE_STATUTES,
  CONSENT_TYPE.CHARTER,
  CONSENT_TYPE.TERMS,
  CONSENT_TYPE.PRIVACY,
]

export const MEMBER_REQUIRED_CONSENTS: ConsentType[] = [
  CONSENT_TYPE.INTERNAL_RULES,
  CONSENT_TYPE.CHARTER,
  CONSENT_TYPE.TERMS,
  CONSENT_TYPE.PRIVACY,
]
